GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImZ1bGxOYW1lIjoiUmlkYSIsInVzZXJuYW1lIjoiY2hvcmlkYWhCIiwiZW1haWwiOiJjaG9yaWRhaGIxM0BnbWFpbC5jb20iLCJhZGRyZXNzIjoiSmwuIEFzbGltaXlhaCBMZXJhbiIsImNvbnRhY3ROdW1iZXIiOiIwODIxMzE3MzEyNzkiLCJjb21wYW55IjoiUFQgR3Jlc2tpdCIsImlhdCI6MTY2MDU3MDQ5MiwiZXhwIjoxNjYwNTcwNTA3fQ.lwJ3XCYaDOt_YfPPtbMG7pJniyjTV3p4tW5HOV7yBKs

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "fullName": "Chozain",
    "username": "ZAIN",
    "email": "bahaque03@gmail.com",
    "address": "Jl. Aslimiyah Leran",
    "contactNumber": "082131731279",
    "company": "PT Greskit",
    "password": "0987poiu",
    "confirmPassword": "0987poiu"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "choridahB",
    "password": "0987poiu"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout